### ISSUE TITLE
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by Logan-lxw** [MoreanP/CSRO#1]
When I try to run the code in Win_64,I meet an error like this.But I download the mujoco200 and mujpro131 with win64 version.So how can I deal with this problem? Thank you!
```
Traceback (most recent call last):
  File "C:\Users\LXV\Desktop\RLCode\CSRO-master\CSRO-master\policy_train.py", line 16, in <module>
    from rlkit.envs.wrappers import NormalizedBoxEnv
  File "C:\Users\LXV\Desktop\RLCode\CSRO-master\CSRO-master\rlkit\envs\__init__.py", line 52, in <module>
    importlib.import_module('rlkit.envs.' + module)
  File "C:\Users\LXV\anaconda3\envs\CSRO-cuda11.0-torch1.7\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\LXV\Desktop\RLCode\CSRO-master\CSRO-master\rlkit\envs\non_mujoco_ant_dir.py", line 2, in <module>
    from gym import spaces
  File "C:\Users\LXV\Desktop\RLCode\CSRO-master\CSRO-master\rand_param_envs\gym\__init__.py", line 5, in <module>
    from rand_param_envs.gym import error
  File "C:\Users\LXV\Desktop\RLCode\CSRO-master\CSRO-master\rand_param_envs\__init__.py", line 1, in <module>
    from rand_param_envs.base import MetaEnv
  File "C:\Users\LXV\Desktop\RLCode\CSRO-master\CSRO-master\rand_param_envs\base.py", line 2, in <module>
    from rand_param_envs.gym.envs.mujoco import MujocoEnv
  File "C:\Users\LXV\Desktop\RLCode\CSRO-master\CSRO-master\rand_param_envs\gym\envs\mujoco\__init__.py", line 1, in <module>
    from rand_param_envs.gym.envs.mujoco.mujoco_env import MujocoEnv
  File "C:\Users\LXV\Desktop\RLCode\CSRO-master\CSRO-master\rand_param_envs\gym\envs\mujoco\mujoco_env.py", line 11, in <module>
    from rand_param_envs import mujoco_py
  File "C:\Users\LXV\Desktop\RLCode\CSRO-master\CSRO-master\rand_param_envs\mujoco_py\__init__.py", line 4, in <module>
    from .mjviewer import MjViewer
  File "C:\Users\LXV\Desktop\RLCode\CSRO-master\CSRO-master\rand_param_envs\mujoco_py\mjviewer.py", line 7, in <module>
    from . import mjcore, mjconstants, glfw
  File "C:\Users\LXV\Desktop\RLCode\CSRO-master\CSRO-master\rand_param_envs\mujoco_py\mjcore.py", line 6, in <module>
    from .mjlib import mjlib
  File "C:\Users\LXV\Desktop\RLCode\CSRO-master\CSRO-master\rand_param_envs\mujoco_py\mjlib.py", line 21, in <module>
    mjlib = cdll.LoadLibrary(os.path.abspath(libfile))
  File "C:\Users\LXV\anaconda3\envs\CSRO-cuda11.0-torch1.7\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\LXV\anaconda3\envs\CSRO-cuda11.0-torch1.7\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

Process finished with exit code 1
```

**Comment by MoreanP** [comment]
My code was written on Linux and has not been tested on Windows. This shouldn't be a code issue, it's a library issue. You can try this: https://github.com/openai/mujoco-py/issues/223

**Comment by congsh1204** [comment]
`
import module: non_mujoco_half_cheetah_vel
import module: non_mujoco_ant_dir
import module: non_mujoco_point_robot
`
What should I do if the corresponding files for these environments do not have a step function？Thank you!

**Comment by MoreanP** [comment]
> `import module: non_mujoco_half_cheetah_vel import module: non_mujoco_ant_dir import module: non_mujoco_point_robot` What should I do if the corresponding files for these environments do not have a step function？Thank you!

The code for the environment is inherited from FOCAL(https://github.com/LanqingLi1993/FOCAL-ICLR), and the non_mujoco environment in FOCAL does not have a step function. Our experiment was conducted on mujoco, not non_mujoco. If you have installed mujoco, you need to:

export MUJOCO_PY_MJPRO_PATH=~/.mujoco/mujoco200

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/.mujoco/mujoco200/bin

**Comment by congsh1204** [comment]
> > `import module: non_mujoco_half_cheetah_vel import module: non_mujoco_ant_dir import module: non_mujoco_point_robot` What should I do if the corresponding files for these environments do not have a step function？Thank you!
> 
> The code for the environment is inherited from FOCAL(https://github.com/LanqingLi1993/FOCAL-ICLR), and the non_mujoco environment in FOCAL does not have a step function. Our experiment was conducted on mujoco, not non_mujoco. If you have installed mujoco, you need to:
> 
> export MUJOCO_PY_MJPRO_PATH=~/.mujoco/mujoco200
> 
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/.mujoco/mujoco200/bin


Thank you for your response, my question has been resolved.
